sudo: required
dist: trusty
language: generic

notifications:
  email:
    on_success: always
    on_failure: always
#    recipients:
#      - jane@doe

env:
  matrix:
    - ROS_DISTRO="indigo"   ROS_REPO=ros               UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="indigo"   ROS_REPO=ros-shadow-fixed  UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="kinetic"  ROS_REPO=ros               UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="kinetic"  ROS_REPO=ros-shadow-fixed  UPSTREAM_WORKSPACE=file
  global:
    - BEFORE_SCRIPT='touch $CATKIN_WORKSPACE/src/ros-industrial/industrial_experimental/IRC_v2/CATKIN_IGNORE'

matrix:
  allow_failures:
    - env: ROS_DISTRO="indigo"  ROS_REPO=ros               UPSTREAM_WORKSPACE=file
    - env: ROS_DISTRO="indigo"  ROS_REPO=ros-shadow-fixed  UPSTREAM_WORKSPACE=file

install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
